**N维数组是机器学习和神经网络的主要数据结构**

下列是不同维度的数据表示
![image-20220301184850670](李沐深度学习.assets/image-20220301184850670.png)<img src="李沐深度学习.assets/image-20220301184934262.png" alt="image-20220301184934262" />

### 创建数组

* 创建数组需要
  * 形状：例如3*4的矩阵
  * 每个元素的数据类型：例如32位浮点数
  * 每个元素的值，例如全部是0，或者随机数

### 访问元素

![image-20220301185106090](李沐深度学习.assets/image-20220301185106090.png)

### 数据操作
首先需要导入`torch`

In [1]:
import torch

张量表示一个数值组成的数组，这个数组可能有多个维度

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape  #这是一个1*12的数组

torch.Size([12])

In [4]:
x = x.reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
x.shape  #torch.Size([3, 4])

torch.Size([3, 4])

In [12]:
new_tensor = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(new_tensor.shape)
new_tensor

torch.Size([3, 4])


tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### 按元素运算
常见的标准运算符 + - * / **

In [13]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

按元素指数运算

In [14]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

多个张量进行连接 concat ,dim = 0表示纵向连接，dim=1表示横向连接

In [20]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]))

In [23]:
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

通过逻辑运算符构建二维张量

In [24]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对张量中所有的元素进行求和

In [25]:
X.sum()

tensor(66.)

### 将张量与numpy互转

In [26]:
x = torch.tensor([1.0, 2, 4, 8])
ndarray1 = x.numpy()
tensor1 = torch.tensor(ndarray1)
print(type(ndarray1), type(tensor1))
ndarray1, tensor1

<class 'numpy.ndarray'> <class 'torch.Tensor'>


(array([1., 2., 4., 8.], dtype=float32), tensor([1., 2., 4., 8.]))

将单个元素的张量转换为python标量

In [31]:
tensor2 = torch.tensor([1])
print(int(tensor2))

1


### 数据预处理
创建一个人工数据集，并存储在csv（逗号分隔值）文件中

In [33]:
import os

os.makedirs(os.path.join('.', 'data'), exist_ok=True)
data_file = os.path.join('.', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

利用pandas从csv文件中读取数据

In [2]:
import pandas as pd

data = pd.read_csv("./data/house_tiny.csv")
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

#### 缺失值处理
一般的缺失值处理方法包括两种，一种是**插值**，一种是**删除**

In [4]:
# 数据分割，将前两列作为输入，最后一列价格作为输出
input_data, output_data = data.iloc[:, 0:2], data.iloc[:, 2]
input_data, output_data

(   NumRooms Alley
 0       NaN  Pave
 1       2.0   NaN
 2       4.0   NaN
 3       NaN   NaN,
 0    127500
 1    106000
 2    178100
 3    140000
 Name: Price, dtype: int64)

针对数值型的缺失值填充

In [15]:
input_data.iloc[:, 0] = input_data.iloc[:, 0].fillna(input_data.iloc[:, 0].mean())
input_data

NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

针对非数值类型或者离散值,将NaN视为一个类别

In [16]:
input_data = pd.get_dummies(input_data, dummy_na=True)
input_data

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [19]:
# 现在 所有的输入和输出都是数值类型,可以将他们转换为张量了
X, y = torch.tensor(input_data.values), torch.tensor(output_data.values)
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

### 线性代数操作的实现

In [5]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [6]:
# 矩阵的转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [7]:
B = torch.arange(24).reshape(2, 3, 4)
B

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [9]:
# 三维张量的转置
B.T

tensor([[[ 0, 12],
         [ 4, 16],
         [ 8, 20]],

        [[ 1, 13],
         [ 5, 17],
         [ 9, 21]],

        [[ 2, 14],
         [ 6, 18],
         [10, 22]],

        [[ 3, 15],
         [ 7, 19],
         [11, 23]]])

In [15]:
B.sum(axis=2, keepdims=True)

tensor([[[ 6],
         [22],
         [38]],

        [[54],
         [70],
         [86]]])

In [20]:
# 计算Ax
A = torch.arange(6).reshape(2, 3)
x = torch.arange(3)  # torch.Size([3]) 即3*1?
print(A.shape, x.shape)
A, x, torch.mv(A, x)

torch.Size([2, 3]) torch.Size([3])


(tensor([[0, 1, 2],
         [3, 4, 5]]),
 tensor([0, 1, 2]),
 tensor([ 5, 14]))

#### 求范数
向量范数
![image-20220301222404792](李沐深度学习.assets/image-20220301222404792.png)
![image-20220301222156741](李沐深度学习.assets/image-20220301222156741.png)

In [26]:
t1 = torch.tensor([3.0,4.0])
# 第二范数
print("t1的第二范数是:",torch.norm(t1)) #5

t1的第二范数是: tensor(5.)


In [25]:
# 第一范数
print("t1的第一范数是:",torch.abs(t1).sum())

t1的第一范数是: tensor(7.)


矩阵范数
![image-20220301222551889](李沐深度学习.assets/image-20220301222551889.png)

In [29]:
X = torch.ones((4,9))
print("矩阵的F范数是",torch.norm(X))

矩阵的F范数是 tensor(6.)


### [自动梯度(导数)](./01计算梯度.py)
X是列向量,假设我们想计算函数y = 2(X)TX的导数
- 创建一个Tensor时，使用requires_grad参数指定是否记录对其的操作，以便之后利用backward()方法进行梯度求解。
- 一个Tensor的requires_grad成员保存该Tensor是否记录操作用于计算梯度。
- 可利用requires_grad_()方法修改Tensor的requires_grad属性（in place）。
- 通过运算创建的Tensor，会自动被赋值grad_fn属性。该属性表示梯度函数。
- 最后得到的Tensor执行自身的backward()函数，此时之前参与运算并生成当前Tensor的叶子（leaf）Tensor将会保存其梯度在叶子Tensor的**grad属性**中。backward()函数接受参数，表示在特定位置求梯度值，该参数应和调用backward()函数的Tensor的维度相同，或者是可broadcast的维度。默认为torch.tensor(1)，也就是在当前梯度为标量1的位置求叶子Tensor的梯度。
- 默认同一个运算得到的Tensor**仅能进行一次**backward()。再次运算得到的Tesnor，可以再次进行backward()。
  当多个Tensor从相同的源Tensor运算得到，这些运算得到的Tensor的backwards()方法将向源Tensor的grad属性中进行数值累加。


In [34]:
import torch
# 在计算y关于x的梯度之前,需要一个地方来存储梯度
X = torch.arange(4.0, requires_grad=True)
y = 2 * torch.dot(X.T,X)
y

tensor(28., grad_fn=<MulBackward0>)

In [39]:
# 反向传播,计算y关于X的每个分量的梯度
y.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [40]:
X = torch.arange(4.0, requires_grad=True)
y = 2 * torch.dot(X.T,X)
y

tensor(28., grad_fn=<MulBackward0>)

In [51]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b *= 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c


# a = torch.randn(size=(), requires_grad=True)
a = torch.tensor([-1.],requires_grad=True)
d = f(a)
print(d)
d.backward()
print(a.grad == d/a)

tensor([-102400.], grad_fn=<MulBackward0>)
tensor([True])


In [1]:
from math import *


a = range(1,25000000)
def f(x):
    return 3*log(x)+cos(x)**2

%timeit r=[f(x) for x in a]

5.09 s ± 45.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


1.10.2
False
tensor([[ 0.0645,  0.3793,  0.0508,  ..., -1.6828, -1.0413,  0.9780],
        [-0.6240,  0.6167,  0.0706,  ...,  0.6830, -0.1293,  1.4136],
        [-0.8391, -0.2817,  0.2736,  ..., -0.6423, -0.4607,  0.8418],
        ...,
        [ 0.0670, -1.9527,  0.5183,  ..., -0.3382, -0.0721,  2.0387],
        [ 0.7934,  0.3851,  0.6229,  ..., -1.3612, -1.4998, -0.8457],
        [-1.9041,  0.6491,  0.6812,  ..., -1.3389, -0.3402, -0.7197]])
tensor([[-0.7961, -0.5009,  0.1651,  ...,  0.2702, -1.5625, -0.1663],
        [ 0.0877,  2.1445,  0.0907,  ...,  1.3538,  0.9548,  0.4151],
        [-0.5100,  1.3214, -1.1232,  ...,  0.0318, -0.4367, -0.4583],
        ...,
        [-1.0123,  0.7442, -0.0074,  ..., -3.0024, -0.6712,  0.2720],
        [-1.2504,  1.3340,  0.7088,  ...,  0.1388, -0.5701,  0.3613],
        [-0.9882, -0.1496,  0.7989,  ..., -0.2306,  1.2600,  0.3843]])
cpu 0.622534990310669 tensor(312690.9375)
